### ISSUE TITLE
Adding a way to display the license for the documentation at the bottom of the page

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/sphinx_materialdesign_theme#30]
@mguthaus makes a good point in https://github.com/google/skywater-pdk/issues/118 that we should display the license the documentation is at.

This should probably be a set of settings under `html_theme_options`;
 - License Icon / Badge / Image URL
    * See "buttons" at https://creativecommons.org/about/downloads/
    * See https://shields.io/category/license
 - Link to the license file on GitHub (IE https://github.com/google/skywater-pdk/blob/master/LICENSE or https://github.com/SymbiFlow/symbiflow-arch-defs/blob/master/COPYING)
 - Trove or SPDX identifier value - https://spdx.org/licenses/

**Comment by mithro** [comment]
Also see https://gist.github.com/qvil/5e3ed56c26d784e51424621119cc4028

<blockquote><img src="https://github.githubassets.com/images/modules/gists/gist-og-image.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> Gist</div><div><strong><a href="https://gist.github.com/qvil/5e3ed56c26d784e51424621119cc4028">License Badges for your Project</a></strong></div><div>License Badges for your Project. GitHub Gist: instantly share code, notes, and snippets.</div></blockquote>

**Comment by mithro** [comment]
@daniellimws Any chance you could look at this?

**Comment by mithro** [comment]
It should be noted that the license for the documentation might not be the same as the license for the code repo.

**Comment by daniellimws** [comment]
@mithro I feel that a plain "License" string looks nicer than having the badge in the footer. What do you think?

![image](https://user-images.githubusercontent.com/8130120/90222290-5abe9700-de3e-11ea-8025-e67932679bb7.png)

![image](https://user-images.githubusercontent.com/8130120/90222389-8b9ecc00-de3e-11ea-893c-3c44913bbc0c.png)

**Comment by mithro** [comment]
I do think the non-badge format fits nicer /but/ I do like the badge has the actual license name in it.....

**Comment by daniellimws** [comment]
How about putting the license name in parenthesis, like `License (ISC)`? Or shall I change it to show the badge?

**Comment by mithro** [comment]
Putting the license name in parenthesis seems like an option.

**Comment by daniellimws** [comment]
We could query for the repository's license through the GitHub [api](https://docs.github.com/en/rest/reference/licenses#get-the-license-for-a-repository), so the user would have less things to configure in conf.py, but that would require additional javascript. 

@mithro What do you think, because of #4?

**Comment by mithro** [comment]
@daniellimws I would just make the user set it.
