### ISSUE TITLE
Render footnotes in a nicer manner

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/sphinx_materialdesign_theme#31]
I started using footnotes in the skywater-pdk and they don't look that nice..

![Screenshot from 2020-07-24 14-12-45](https://user-images.githubusercontent.com/21212/88435773-c9688180-cdb7-11ea-819d-f3637149f146.png)

**Comment by daniellimws** [comment]
@mithro Could you add a link to this?

**Comment by mithro** [comment]
Haven't merged this yet, see https://skywater-pdk--127.org.readthedocs.build/en/127/rules/hv.html for example.

We should probably make sure to add some to the example...

**Comment by daniellimws** [comment]
There already are examples [here](https://sphinx-symbiflow-theme.readthedocs.io/en/latest/examples/reStructuredText/footnotes.html).
