### ISSUE TITLE
Table column widths are wrong

### ISSUE THREAD

**Issue by daniellimws** [SymbiFlow/sphinx_materialdesign_theme#33]
![image](https://user-images.githubusercontent.com/8130120/88444776-6aefe180-ce51-11ea-813f-67edba36266b.png)

As seen in https://skywater-pdk.readthedocs.io/en/latest/rules/periphery.html?highlight=poly%20resistor#poly

**Comment by mithro** [comment]
~~FYI - The anchor link there doesn't appear to be working?~~

Actually I lie, it is working...

**Comment by mithro** [comment]
This is what I get...

![Screenshot from 2020-07-24 17-58-23](https://user-images.githubusercontent.com/21212/88445418-5838c680-cdd7-11ea-8479-8e9d4c812758.png)

**Comment by daniellimws** [comment]
@mithro Looks like the header for `Flag` column is also not wide enough? And `(poly.X.1a)` overflowed into the `Description` column?

**Comment by mithro** [comment]
Unclear to me?

**Comment by daniellimws** [comment]
![tablewidth](https://user-images.githubusercontent.com/8130120/88869715-1d56e880-d246-11ea-96bb-33045642bcce.png)

@mithro Look at this. Sorry for the late reply, accidentally missed this comment...

**Comment by mithro** [comment]
I expect it is because I do `:widths:` in the `.. list-table::` like the following;
```rst

:drc_rule:`(nwell.-)`
---------------------

.. list-table:: Function: Define nwell implant regions
   :header-rows: 1
   :stub-columns: 1
   :width: 100%
   :widths: 10 75 5 10
```

**Comment by daniellimws** [comment]
@mithro Wanna change this? Or you think it is ok like this now? I suppose we can't manually set the widths.

**Comment by mithro** [comment]
I would like it to work better, but don't know how to make that happen :-)
