### ISSUE TITLE
Link paragraph mark link thingy not respecting theme colors?

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/sphinx_materialdesign_theme#42]
I recently noticed that the paragraph mark link thingy in the Fomu workshop is SymbiFlow purple rather than Fomu workshop blue.

![image](https://user-images.githubusercontent.com/21212/97095414-04c35800-1614-11eb-829e-1cc6b82132cb.png)

I haven't seen this behaviour on the SkyWater PDK documentation. I'm not sure if it is because the readthedocs output hasn't been regenerated recently or if it is only affecting the blue theme?

**Comment by daniellimws** [comment]
Ahh good catch I forgot to let the symbol inherit the color from the theme
